In [2]:
import numpy as np
import pandas as pd

In [3]:
movies = pd.read_csv('tmdb_5000_movies.csv')
credits = pd.read_csv('tmdb_5000_credits.csv')

In [4]:
movies.head(1)

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,production_countries,release_date,revenue,runtime,spoken_languages,status,tagline,title,vote_average,vote_count
0,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.avatarmovie.com/,19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2009-12-10,2787965087,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800

In [5]:
credits.head(1)

,movie_id,title,cast,crew
0,19995,Avatar,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."

In [6]:
movies = movies.merge(credits,on='title')

Removing Unwanted Columns

In [7]:
movies.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4809 entries, 0 to 4808
Data columns (total 23 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   budget                4809 non-null   int64
 1   genres                4809 non-null   object
 2   homepage              1713 non-null   object
 3   id                    4809 non-null   int64
 4   keywords              4809 non-null   object
 5   original_language     4809 non-null   object
 6   original_title        4809 non-null   object
 7   overview              4806 non-null   object
 8   popularity            4809 non-null   float64
 9   production_companies  4809 non-null   object
 10  production_countries  4809 non-null   object
 11  release_date          4808 non-null   object
 12  revenue               4809 non-null   int64
 13  runtime               4807 non-null   float64
 14  spoken_languages      4809 non-null   object
 15  status                4809 non-null   object
 16  tagline               3965 non-null   object
 17  title                 4809 non-null   object
 18  vote_average          4809 non-null   float64
 19  vote_count            4809 non-null   int64
 20  movie_id              4809 non-null   int64
 21  cast                  4809 non-null   object
 22  crew                  4809 non-null   object
dtypes: float64(3), int64(5), object(15)
memory usage: 864.2+ KB

In [8]:
movies = movies [['movie_id','title','overview','genres','keywords','cast','crew']]

In [9]:
movies.isnull().sum()

movie_id    0
title       0
overview    3
genres      0
keywords    0
cast        0
crew        0
dtype: int64

In [10]:
movies.dropna(inplace = True)

In [11]:
 movies.duplicated().sum()

np.int64(0)

In [12]:
movies.iloc[0].genres

'[{"id": 28, "name": "Action"}, {"id": 12, "name": "Adventure"}, {"id": 14, "name": "Fantasy"}, {"id": 878, "name": "Science Fiction"}]'

In [13]:
import ast

def convert(obj):
    L = []
    
    if isinstance(obj, str):    
        obj = ast.literal_eval(obj)
        
    for i in obj:
        L.append(i['name'])
        
    return L

In [14]:
import ast 
ast.literal_eval(
'[{"id": 28, "name": "Action"}, {"id": 12, "name": "Adventure"}, {"id": 14, "name": "Fantasy"}, {"id": 878, "name": "Science Fiction"}]')

[{'id': 28, 'name': 'Action'},
 {'id': 12, 'name': 'Adventure'},
 {'id': 14, 'name': 'Fantasy'},
 {'id': 878, 'name': 'Science Fiction'}]

In [15]:
movies['genres'].apply(convert)

0       [Action, Adventure, Fantasy, Science Fiction]
1                        [Adventure, Fantasy, Action]
2                          [Action, Adventure, Crime]
3                    [Action, Crime, Drama, Thriller]
4                [Action, Adventure, Science Fiction]
                            ...
4804                        [Action, Crime, Thriller]
4805                                [Comedy, Romance]
4806               [Comedy, Drama, Romance, TV Movie]
4807                                               []
4808                                    [Documentary]
Name: genres, Length: 4806, dtype: object

In [16]:
movies['genres'] =  movies['genres'].apply(convert)

In [17]:
movies.head(1)

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[Action, Adventure, Fantasy, Science Fiction]","[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...","[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."

In [18]:
movies['keywords'] =  movies['keywords'].apply(convert)

In [19]:
movies.head(1)

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[Action, Adventure, Fantasy, Science Fiction]","[culture clash, future, space war, space colon...","[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."

In [20]:
# def convert3(obj):
#     L = []
#     counter = 0 
#     for i in  ast.literal_eval(obj):
#         if counter != 3:
#         L.append(i['name'])
#         counter +=1
#      else:
#          break
#     return L


import ast

def convert3(obj):
    L = []
    counter = 0
    obj = ast.literal_eval(obj)   # convert string to list
    
    for i in obj:
        if counter != 3:
            L.append(i['name'])
            counter += 1
        else:
            break
            
    return L

# Assistant
The error occurs because of incorrect indentation in your code. Python is very sensitive to indentation as it uses it to define code blocks.

Would you like me to provide the corrected code?

In [21]:
movies['cast'] = movies['cast'].apply(convert3)

Now we only want director name from crew taht a big deal lets do it

In [22]:
import ast

def fetch_director(obj):
    L = []
    for i in ast.literal_eval(obj):
        if i['job'] == 'Director':
            L.append(i['name'])
            break
    return L

In [23]:
movies['crew'] = movies['crew'].apply(fetch_director)

In [24]:
movies['overview'][0]

'In the 22nd century, a paraplegic Marine is dispatched to the moon Pandora on a unique mission, but becomes torn between following orders and protecting an alien civilization.'

In [25]:
movies['overview'] = movies['overview'].apply(lambda x:x.split())

In [26]:
movies.head(3)

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"[In, the, 22nd, century,, a, paraplegic, Marin...","[Action, Adventure, Fantasy, Science Fiction]","[culture clash, future, space war, space colon...","[Sam Worthington, Zoe Saldana, Sigourney Weaver]",[James Cameron]
1,285,Pirates of the Caribbean: At World's End,"[Captain, Barbossa,, long, believed, to, be, d...","[Adventure, Fantasy, Action]","[ocean, drug abuse, exotic island, east india ...","[Johnny Depp, Orlando Bloom, Keira Knightley]",[Gore Verbinski]
2,206647,Spectre,"[A, cryptic, message, from, Bond’s, past, send...","[Action, Adventure, Crime]","[spy, based on novel, secret agent, sequel, mi...","[Daniel Craig, Christoph Waltz, Léa Seydoux]",[Sam Mendes]

In [27]:
  movies['genres'] = movies['genres'].apply(lambda x:[i.replace(" ","") for i in x])

In [28]:
  movies['keywords'] = movies['keywords'].apply(lambda x:[i.replace(" ","") for i in x])
  movies['cast'] = movies['cast'].apply(lambda x:[i.replace(" ","") for i in x])
  movies['crew'] = movies['crew'].apply(lambda x:[i.replace(" ","") for i in x])

In [29]:
movies.head(3)

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"[In, the, 22nd, century,, a, paraplegic, Marin...","[Action, Adventure, Fantasy, ScienceFiction]","[cultureclash, future, spacewar, spacecolony, ...","[SamWorthington, ZoeSaldana, SigourneyWeaver]",[JamesCameron]
1,285,Pirates of the Caribbean: At World's End,"[Captain, Barbossa,, long, believed, to, be, d...","[Adventure, Fantasy, Action]","[ocean, drugabuse, exoticisland, eastindiatrad...","[JohnnyDepp, OrlandoBloom, KeiraKnightley]",[GoreVerbinski]
2,206647,Spectre,"[A, cryptic, message, from, Bond’s, past, send...","[Action, Adventure, Crime]","[spy, basedonnovel, secretagent, sequel, mi6, ...","[DanielCraig, ChristophWaltz, LéaSeydoux]",[SamMendes]

In [52]:
movies['tags'] = movies['overview'] + movies['genres'] + movies['keywords'] + movies['cast'] + movies['crew']

In [53]:
movies.head(3)

,movie_id,title,overview,genres,keywords,cast,crew,tags
0,19995,Avatar,"[In, the, 22nd, century,, a, paraplegic, Marin...","[Action, Adventure, Fantasy, ScienceFiction]","[cultureclash, future, spacewar, spacecolony, ...","[SamWorthington, ZoeSaldana, SigourneyWeaver]",[JamesCameron],"[In, the, 22nd, century,, a, paraplegic, Marin..."
1,285,Pirates of the Caribbean: At World's End,"[Captain, Barbossa,, long, believed, to, be, d...","[Adventure, Fantasy, Action]","[ocean, drugabuse, exoticisland, eastindiatrad...","[JohnnyDepp, OrlandoBloom, KeiraKnightley]",[GoreVerbinski],"[Captain, Barbossa,, long, believed, to, be, d..."
2,206647,Spectre,"[A, cryptic, message, from, Bond’s, past, send...","[Action, Adventure, Crime]","[spy, basedonnovel, secretagent, sequel, mi6, ...","[DanielCraig, ChristophWaltz, LéaSeydoux]",[SamMendes],"[A, cryptic, message, from, Bond’s, past, send..."

In [54]:
new_df = movies[['movie_id','title','tags']].copy()

In [55]:
new_df

,movie_id,title,tags
0,19995,Avatar,"[In, the, 22nd, century,, a, paraplegic, Marin..."
1,285,Pirates of the Caribbean: At World's End,"[Captain, Barbossa,, long, believed, to, be, d..."
2,206647,Spectre,"[A, cryptic, message, from, Bond’s, past, send..."
3,49026,The Dark Knight Rises,"[Following, the, death, of, District, Attorney..."
4,49529,John Carter,"[John, Carter, is, a, war-weary,, former, mili..."
...,...,...,...
4804,9367,El Mariachi,"[El, Mariachi, just, wants, to, play, his, gui..."
4805,72766,Newlyweds,"[A, newlywed, couple's, honeymoon, is, upended..."
4806,231617,"Signed, Sealed, Delivered","[""Signed,, Sealed,, Delivered"", introduces, a,..."
4807,126186,Shanghai Calling,"[When, ambitious, New, York, attorney, Sam, is..."
4808,25975,My Date with Drew,"[Ever, since, the, second, grade, when, he, fi..."

In [56]:
new_df['tags'] = new_df['tags'].apply(lambda x: " ".join(x))

In [41]:
new_df['tags'] = new_df['tags'].apply(lambda x:" ".join(x))

C:\Users\ganesh jadhav\AppData\Local\Temp\ipykernel_7752\3089450492.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['tags'] = new_df['tags'].apply(lambda x:" ".join(x))

In [57]:
new_df['tags'][0]

'In the 22nd century, a paraplegic Marine is dispatched to the moon Pandora on a unique mission, but becomes torn between following orders and protecting an alien civilization. Action Adventure Fantasy ScienceFiction cultureclash future spacewar spacecolony society spacetravel futuristic romance space alien tribe alienplanet cgi marine soldier battle loveaffair antiwar powerrelations mindandsoul 3d SamWorthington ZoeSaldana SigourneyWeaver JamesCameron'

In [58]:
new_df['tags'] = new_df['tags'].str.lower()

In [59]:
print(new_df['tags'][0])

in the 22nd century, a paraplegic marine is dispatched to the moon pandora on a unique mission, but becomes torn between following orders and protecting an alien civilization. action adventure fantasy sciencefiction cultureclash future spacewar spacecolony society spacetravel futuristic romance space alien tribe alienplanet cgi marine soldier battle loveaffair antiwar powerrelations mindandsoul 3d samworthington zoesaldana sigourneyweaver jamescameron

In [84]:
from nltk.stem.porter import PorterStemmer
ps = PorterStemmer()

In [85]:
def stem(text):
    y = []
    for i in text.split():
        y.append(ps.stem(i))
        return" ".join(y)

In [86]:
 new_df['tags'] = new_df['tags'].apply(stem)

In [87]:
!pip install nltk

Requirement already satisfied: nltk in d:\anaconda\lib\site-packages (3.9.2)
Requirement already satisfied: click in d:\anaconda\lib\site-packages (from nltk) (8.2.1)
Requirement already satisfied: joblib in d:\anaconda\lib\site-packages (from nltk) (1.5.2)
Requirement already satisfied: regex>=2021.8.3 in d:\anaconda\lib\site-packages (from nltk) (2025.9.1)
Requirement already satisfied: tqdm in d:\anaconda\lib\site-packages (from nltk) (4.67.1)
Requirement already satisfied: colorama in d:\anaconda\lib\site-packages (from click->nltk) (0.4.6)

In [88]:
from sklearn.feature_extraction.text import CountVectorizer

cv = CountVectorizer(max_features=5000, stop_words='english')

cv.fit_transform(new_df['tags']).toarray()

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], shape=(4806, 1276))

In [89]:
vectors[0]   # first movie

array([0, 0, 0, ..., 0, 0, 0], shape=(5000,))

In [94]:
cv.get_feature_names_out()

array(['100', '11', '12', ..., 'zohre', 'zombi', 'zoo'],
      shape=(1276,), dtype=object)

In [95]:
list(cv.get_feature_names_out())

['100',
 '11',
 '12',
 '15',
 '16',
 '17',
 '1910',
 '1921',
 '1950',
 '1971',
 '1982',
 '20',
 '200',
 '2009',
 '2016',
 '2046',
 '20th',
 '28',
 '400',
 '48',
 '66',
 '6th',
 '70',
 '84',
 '86',
 '88',
 'aaa',
 'aaron',
 'abbi',
 'abortionist',
 'academi',
 'accid',
 'accomplish',
 'action',
 'actress',
 'adam',
 'adapt',
 'admir',
 'admit',
 'adopt',
 'adventur',
 'adverti',
 'affabl',
 'age',
 'aged',
 'agent',
 'aibileen',
 'aidan',
 'aileen',
 'aim',
 'ajami',
 'alan',
 'albert',
 'alcohol',
 'alex',
 'alexander',
 'alexia',
 'alic',
 'alice',
 'alien',
 'alli',
 'altruist',
 'alyssa',
 'amalia',
 'amanda',
 'ambiti',
 'america',
 'american',
 'amiabl',
 'amidst',
 'anakin',
 'andi',
 'andrew',
 'angela',
 'angie',
 'anim',
 'annabel',
 'annie',
 'anton',
 'apart',
 'approach',
 'aragorn',
 'archaeologist',
 'archetyp',
 'archiv',
 'ari',
 'arkin',
 'arm',
 'arn',
 'arrogant',
 'art',
 'arthur',
 'arti',
 'ash',
 'ashitaka',
 'aspect',
 'aspir',
 'assassin',
 'astronaut',
 'astérix',
 'athlet',
 'august',
 'aussi',
 'australian',
 'austrian',
 'author',
 'autobiograph',
 'autumn',
 'awkward',
 'ayurveda',
 'ba',
 'babe',
 'babi',
 'bachelor',
 'backup',
 'bahia',
 'balthazar',
 'bambi',
 'bank',
 'baptist',
 'barney',
 'barri',
 'base',
 'bathori',
 'batman',
 'beatric',
 'beauti',
 'beautiful',
 'becau',
 'becca',
 'befor',
 'begin',
 'behrani',
 'believ',
 'belka',
 'bella',
 'ben',
 'benjamin',
 'berlin',
 'best',
 'beth',
 'betray',
 'better',
 'betti',
 'bi',
 'bianca',
 'biker',
 'bilbo',
 'billi',
 'billionair',
 'biograph',
 'biographi',
 'bird',
 'bizarr',
 'blend',
 'bob',
 'bobbi',
 'bolt',
 'bond',
 'boog',
 'book',
 'bore',
 'born',
 'bounc',
 'bound',
 'bounti',
 'bourn',
 'boy',
 'boyz',
 'brad',
 'brandon',
 'brave',
 'break',
 'breast',
 'bree',
 'brennan',
 'brian',
 'brick',
 'bridget',
 'brilliant',
 'britain',
 'british',
 'britt',
 'brokeback',
 'brooklyn',
 'bruce',
 'bubba',
 'buck',
 'bucum',
 'bud',
 'bueno',
 'bug',
 'bumbl',
 'burger',
 'businessman',
 'cab',
 'cabbie',
 'cadi',
 'caiu',
 'cal',
 'cale',
 'caleb',
 'calvin',
 'capitol',
 'capt',
 'captain',
 'captiv',
 'captur',
 'carl',
 'carmen',
 'carol',
 'carolin',
 'carrie',
 'cedric',
 'celest',
 'celestin',
 'centuri',
 'challeng',
 'chao',
 'chapman',
 'charl',
 'charli',
 'charlie',
 'charlott',
 'chart',
 'chauffeur',
 'cheese',
 'chelio',
 'chicago',
 'childhood',
 'chili',
 'chon',
 'chri',
 'chrissi',
 'christin',
 'christina',
 'christma',
 'chronolog',
 'chuck',
 'chucki',
 'chuckie',
 'cia',
 'cidad',
 'cindi',
 'circu',
 'citi',
 'clair',
 'clarenc',
 'clark',
 'class',
 'clay',
 'clear',
 'climb',
 'cobb',
 'cocki',
 'codi',
 'cohabit',
 'col',
 'colin',
 'colleg',
 'colonel',
 'columbu',
 'com',
 'combat',
 'come',
 'comedi',
 'commentator',
 'commerci',
 'commun',
 'complet',
 'comput',
 'conni',
 'conrad',
 'construct',
 'contact',
 'continu',
 'control',
 'conveni',
 'corki',
 'corky',
 'corpor',
 'countless',
 'cousins',
 'cover',
 'crack',
 'craig',
 'creat',
 'crew',
 'cross',
 'cur',
 'cw',
 'dahlia',
 'dale',
 'damon',
 'dan',
 'danger',
 'daniel',
 'danni',
 'danny',
 'dar',
 'dariu',
 'darren',
 'daryl',
 'date',
 'dave',
 'david',
 'dawn',
 'deadpool',
 'deal',
 'dean',
 'deckard',
 'decor',
 'dedic',
 'deep',
 'deepli',
 'deform',
 'denni',
 'dentist',
 'depress',
 'depression',
 'deputi',
 'der',
 'derek',
 'desper',
 'despit',
 'despond',
 'detect',
 'determin',
 'detroit',
 'deuc',
 'dev',
 'dex',
 'diamond',
 'diego',
 'diplomats',
 'direct',
 'director',
 'dirti',
 'discov',
 'disench',
 'disgrac',
 'dispatch',
 'district',
 'disturb',
 'doctor',
 'documentari',
 'dogtown',
 'domen',
 'don',
 'donato',
 'donna',
 'doormat',
 'dorian',
 'dorothi',
 'dorothy',
 'double',
 'doug',
 'dr',
 'dracula',
 'dragon',
 'drama',
 'dramat',
 'dramati',
 'drawn',
 'dray',
 'dream',
 'drew',
 'drina',
 'driven',
 'driver',
 'du',
 'duet',
 'duffi',
 'duncan',
 'dunson',
 'dure',
 'dutch',
 'earli',
 'ec',
 'eccentr',
 'eddi',
 'eden',
 'edg',
 'edmond',
 'edward',
 'egyptologist',
 'eighti',
 'el',
 'elektra',
 'eliza',
 'elizabeth',
 'ell',
 'ella',
 'elli',
 'elliot',
 'elmo',
 'elsa',
 'elvi',
 'emili',
 'emma',
 'employ',
 'en',
 'end',
 'enemi',
 'enforc',
 'engin',
 'english',
 'enrag',
 'enter',
 'era',
 'eric',
 'erin',
 'errol',
 'erstwhil',
 'escap',
 'esteem',
 'estrang',
 'ethan',
 'eva',
 'evan',
 'event',
 'everi',
 'everybodi',
 'everyon',
 'everyth',
 'evil',
 'ex',
 'exactli',
 'experi',
 'explor',
 'face',
 'fact',
 'fail',
 'famili',
 'famou',
 'far',
 'fast',
 'fbi',
 'fear',
 'fed',
 'feel',
 'femal',
 'fifti',
 'film',
 'filmmak',
 'financ',
 'firefight',
 'flamboyantli',
 'fledgl',
 'fletcher',
 'folklor',
 'follow',
 'foolish',
 'forc',
 'ford',
 'foren',
 'forks',
 'forrest',
 'foundl',
 'fourteen',
 'fourth',
 'frame',
 'franci',
 'frank',
 'franki',
 'fred',
 'freddi',
 'freddie',
 'freddy',
 'frederick',
 'french',
 'frida',
 'friend',
 'friends',
 'frodo',
 'fugit',
 'furiou',
 'futurist',
 'gabita',
 'gabriel',
 'galaxina',
 'gang',
 'garfield',
 'gari',
 'gary',
 'gen',
 'genet',
 'geophysicist',
 'georg',
 'george',
 'georgia',
 'ghost',
 'gift',
 'gigli',
 'gilbert',
 'gile',
 'girl',
 'given',
 'glendon',
 'glengarri',
 'global',
 'god',
 'godzilla',
 'goo',
 'good',
 'gorgeou',
 'govern',
 'grace',
 'gradi',
 'greed',
 'greg',
 'gretta',
 'griev',
 'griff',
 'gritti',
 'ground',
 'grow',
 'gru',
 'gu',
 'guillermo',
 'guns',
 'gunsl',
 'gwyneth',
 'haley',
 'half',
 'hamlet',
 'hancock',
 'handsome',
 'hanna',
 'hannah',
 'hapless',
 'happi',
 'hard',
 'hardflip',
 'harper',
 'harri',
 'harriet',
 'harry',
 'harvard',
 'hassl',
 'hazen',
 'heartbeep',
 'heather',
 'heaven',
 'held',
 'helen',
 'heli',
 'henri',
 'hi',
 'hick',
 'high',
 'hilarity',
 'hire',
 'histor',
 'histori',
 'hitman',
 'holden',
 'holli',
 'hollywood',
 'home',
 'homicid',
 'hondo',
 'honey',
 'hope',
 'horty',
 'hot',
 'hotshot',
 'housewif',
 'hoyl',
 'hubert',
 'hud',
 'hugo',
 'human',
 'humans',
 'humbert',
 'huo',
 'hushpuppy',
 'ice',
 'iconoclastic',
 'ignor',
 'ike',
 'immedi',
 'immort',
 'indi',
 'indian',
 'industri',
 'innoc',
 'insan',
 'insid',
 'inspir',
 'instead',
 'inter',
 'interstellar',
 'intrepid',
 'inventor',
 'investig',
 'invi',
 'ip',
 'iri',
 'irish',
 'iron',
 'isaac',
 'isabel',
 'ivan',
 'jack',
 'jackass',
 'jacki',
 'jacq',
 'jade',
 'jake',
 'jamal',
 'jame',
 'jami',
 'jan',
 'jane',
 'jare',
 'jarhead',
 'jasmin',
 'jason',
 'jay',
 'jealous',
 'jean',
 'jeffrey',
 'jellyston',
 'jenna',
 'jep',
 'jerri',
 'jess',
 'jessica',
 'jesus',
 'jigsaw',
 'jim',
 'jimi',
 'jimmi',
 'joan',
 'joe',
 'joel',
 'joey',
 'john',
 'johnni',
 'join',
 'jonathan',
 'jordan',
 'joseph',
 'josh',
 'josie',
 'juli',
 'julia',
 'julian',
 'juliu',
 'just',
 'justice',
 'justin',
 'kaisa',
 'kale',
 'karl',
 'katherin',
 'katniss',
 'kay',
 'kazakh',
 'keong',
 'kermit',
 'kevin',
 'kid',
 'kidnapp',
 'kindheart',
 'king',
 'kinsey',
 'kline',
 'krishna',
 'kuzco',
 'kyle',
 'la',
 'lac',
 'lara',
 'larisa',
 'larri',
 'late',
 'lauri',
 'lawrenc',
 'le',
 'led',
 'lee',
 'left',
 'legendari',
 'legless',
 'lestat',
 'lester',
 'level',
 'li',
 'lif',
 'life',
 'lifelong',
 'light',
 'lightheart',
 'lightn',
 'like',
 'lil',
 'lilya',
 'liquid',
 'literatur',
 'liu',
 'live',
 'liz',
 'lizzi',
 'llewelyn',
 'lloyd',
 'lo',
 'lock',
 'lola',
 'london',
 'lone',
 'loner',
 'long',
 'longtim',
 'loo',
 'look',
 'lorrain',
 'lov',
 'love',
 'low',
 'lu',
 'luc',
 'luci',
 'luke',
 'lush',
 'luther',
 'mad',
 'madea',
 'madelin',
 'mafia',
 'maggi',
 'maggie',
 'majo',
 'major',
 'malcolm',
 'mallori',
 'man',
 'mandi',
 'manhattanit',
 'mann',
 'manny',
 'marcel',
 'marcellu',
 'marcu',
 'marguerit',
 'mari',
 'maria',
 'mario',
 'marisa',
 'mark',
 'marshal',
 'marti',
 'martin',
 'mask',
 'master',
 'match',
 'matt',
 'matthew',
 'maurice',
 'maverick',
 'max',
 'maximillian',
 'mcmaster',
 'medic',
 'meet',
 'megaforc',
 'megan',
 'melani',
 'melba',
 'melvin',
 'member',
 'men',
 'menac',
 'mental',
 'merchant',
 'mere',
 'meredith',
 'mexican',
 'mia',
 'michael',
 'michel',
 'mickey',
 'middl',
 'midler',
 'mike',
 'mild',
 'mile',
 'milo',
 'milton',
 'mina',
 'mind',
 'minion',
 'minnesota',
 'minni',
 'minor',
 'mirabel',
 'miracl',
 'miser',
 'mitch',
 'mitchel',
 'modern',
 'molière',
 'molli',
 'mom',
 'moment',
 'money',
 'monro',
 'monster',
 'morgan',
 'mort',
 'mother',
 'motherhood',
 'movi',
 'mowgli',
 'mr',
 'mulder',
 'multi',
 'multipl',
 'mumbl',
 'murderess',
 'murray',
 'music',
 'myle',
 'nacho',
 'nada',
 'naiv',
 'nanni',
 'nat',
 'natali',
 'nathan',
 'natur',
 'navi',
 'nazi',
 'neal',
 'nearli',
 'neighbor',
 'nelli',
 'nelson',
 'nemo',
 'nerdi',
 'nervou',
 'new',
 'newli',
 'newly',
 'newlyw',
 'news',
 'nick',
 'nicky',
 'nicol',
 'nicola',
 'nightclub',
 'ninja',
 'noah',
 'noni',
 'norma',
 'noth',
 'notori',
 'noval',
 'novelist',
 'nypd',
 'obsess',
 'octob',
 'offic',
 'officially',
 'old',
 'oliv',
 'olivi',
 'olli',
 'omar',
 'onc',
 'open',
 'ordinari',
 'orphan',
 'orson',
 'oscar',
 'outlaw',
 'overachiev',
 'packard',
 'palo',
 'paranorm',
 'pari',
 'paris',
 'parker',
 'parol',
 'passion',
 'patron',
 'patti',
 'patton',
 'paul',
 'peggi',
 'penny',
 'pete',
 'peter',
 'phil',
 'photograph',
 'pianist',
 'pierrot',
 'pinnacl',
 'place',
 'plagu',
 'platinum',
 'play',
 'playboy',
 'pleasantli',
 'pledg',
 'po',
 'pobbi',
 'poland',
 'polar',
 'polic',
 'polit',
 'poor',
 'pooti',
 'pop',
 'porter',
 'pot',
 'power',
 'predominantli',
 'prequel',
 'present',
 'presid',
 'pressur',
 'presum',
 'pride',
 'princess',
 'priscilla',
 'privat',
 'pro',
 'profess',
 'professor',
 'prot',
 'psycholog',
 'publish',
 'publisher',
 'quadriplegics',
 'quantum',
 'quentin',
 'quirki',
 'rachel',
 'radio',
 'rafael',
 'rai',
 'raimunda',
 'raju',
 'ramona',
 'rattl',
 'ray',
 'real',
 'rebelli',
 'recent',
 'recently',
 'recess',
 'record',
 'recruit',
 'red',
 'redact',
 'reel',
 'relea',
 'remak',
 'rememb',
 'renegad',
 'renton',
 'report',
 'restless',
 'retir',
 'return',
 'reuben',
 'reunit',
 'rhode',
 'rich',
 'richard',
 'rick',
 'ride',
 'rise',
 'river',
 'rizwan',
 'road',
 'roar',
 'rob',
 'robert',
 'robin',
 'rock',
 'rocket',
 'rocki',
 'rodney',
 'roger',
 'rogu',
 'romant',
 'rooki',
 'rose',
 'rowan',
 'rugrat',
 'russ',
 'russel',
 'russian',
 'ruthless',
 'ryan',
 'ryden',
 'sai',
 ...]

In [99]:
from sklearn.metrics.pairwise import cosine_similarity
similarity = cosine_similarity(vectors)

In [100]:
similarity[0]

array([1.        , 0.08964215, 0.05976143, ..., 0.02519763, 0.02817181,
       0.        ], shape=(4806,))

In [105]:
def recommend(movie):
    movie_index = new_df[new_df['title'] == movie].index[0]
    distances = similarity[movie_index]
    
    movies_list = sorted(list(enumerate(distances)), reverse=True, key=lambda x: x[1])[1:6]

    for i in movies_list:
        print(new_df.iloc[i[0]].title)

In [107]:
recommend('Batman Begins')

The Dark Knight
The Dark Knight Rises
Batman
Batman & Robin
Batman

In [108]:
import pickle

pickle.dump(new_df,open('movies.pkl','wb'))

In [109]:
pickle.dump(new_df.to_dict(),open('movie_dict.pkl','wb'))

In [110]:
pickle.dump(similarity, open('similarity.pkl','wb'))